from enum import Enum


class Role(Enum):
    CUSTOMER = "CUSTOMER"
    SYSTEM_ADMINISTRATOR = "SYSTEM_ADMINISTRATOR"
    CONTROLLER = "CONTROLLER"
    CUSTOMER_ADMINISTRATOR = "CUSTOMER_ADMINISTRATOR"


class PaymentType(Enum):
    CARD = "CARD"
    PAYPAL = "PAYPAL"
